### PR TITLE
1.19.1 fixes

### PR DESCRIPTION
**Pull request by atenfyr**
Fix for #11. Note that my changes are incompatible with 1.19, I expect you will want to adjust your version detection scheme if you want to maintain support for 1.19 because currently the plugin sees 1.19 and 1.19.1 as the same version.

### CODE REVIEW

**Comment by mega12345mega** [comment]
I was about to start fixing it myself! :D

If [Bukkit.getVersion()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#getVersion()) works like I think it should, I'm guessing it would be pretty straightforward to split `compatibility.v1_19_R1` into `compatibility.v1_19_R1_0` (how it is currently) and `compatibility.v1_19_R1_1` (this pull request).

[Compatibility#63](https://github.com/Doclic/NoEncryption/blob/d70c51cacd155e2742aa6e506ffbf9d6403ee0c6/src/main/java/me/doclic/noencryption/compatibility/Compatibility.java#L63) would become:
```
final String subVersion = (Bukkit.getVersion().equals("1.19") ? "_0" : (Bukkit.getVersion().equals("1.19.1") ? "_1" : ""));
final Class<?> compatibleClass = Class.forName(versionPackage + "." + clazz.getSimpleName() + "_" + minecraftVersion + subVersion);
```

**Comment by Edgeburn** [comment]
I'm probably just missing something, but I can't seem to compile this. I've run the Spigot build tools for 1.19 and 1.19.1, but when I run `mvn package` the build fails with this

```
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< me.doclic:NoEncryption >-----------------------
[INFO] Building NoEncryption 2.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.556 s
[INFO] Finished at: 2022-08-01T20:35:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project NoEncryption: Could not resolve dependencies for project me.doclic:NoEncryption:jar:2.0: org.spigotmc:spigot:jar:remapped-mojang:1.19.1-R0.1-SNAPSHOT was not found in https://repo.papermc.io/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of papermc has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by atenfyr** [comment]
> I'm probably just missing something, but I can't seem to compile this. I've run the Spigot build tools for 1.19 and 1.19.1, but when I run `mvn package` the build fails with this

I would make sure you have built Spigot with the flag for remapping the jar with Mojang mappings:
`java -jar BuildTools.jar --rev 1.19.1 --remapped`

I'm also not entirely sure why the plugin references the Paper API, it is unused and its dependency can be safely removed

**Comment by Edgeburn** [comment]
> > I'm probably just missing something, but I can't seem to compile this. I've run the Spigot build tools for 1.19 and 1.19.1, but when I run `mvn package` the build fails with this
> 
> I would make sure you have built Spigot with the flag for remapping the jar with Mojang mappings: `java -jar BuildTools.jar --rev 1.19.1 --remapped`
> 

I was able to successfully build the jar with the Mojang mappings; thanks!

**Comment by dylif** [comment]
Just wanted to chip in. Compiled this PR from source and works great. Hopefully we can see this in.

**Comment by analogged** [comment]
Can someone provide the compiled jar?

**Comment by dylif** [comment]
> Can someone provide the compiled jar?

I would recommend switching to this plugin https://github.com/Oharass/FreedomChat

**Comment by V1nc3ntWasTaken** [comment]
Hiyo, I'm V1nc3ntWasTaken, And I was surrendered, and now overseeing the project of Doclic/NoEncryption. Due to this event, and some back end conflicting changes that were performed earlier today (9/18/2022), I will be adding 1.19.1 support on my end. Thank you, and sorry.

**Comment by atenfyr** [comment]
> Hiyo, I'm V1nc3ntWasTaken, And I was surrendered, and now overseeing the project of Doclic/NoEncryption. Due to this event, and some back end conflicting changes that were performed earlier today (9/18/2022), I will be adding 1.19.1 support on my end. Thank you, and sorry.

Thanks for your good work fixing this plugin up after the original developer seems to have abandoned it out of nowhere. The code for making all messages system messages is very simple, so all I suggest is that you try to keep your own solution simple as well. If you wind up using any code from my original fix, just please provide credit :)

**Pull request closed without merging**
